spring.application.name=literalura
# Banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/literalura
spring.datasource.username=postgres
spring.datasource.password=SUA_SENHA_AQUI

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Virtual Threads (Java 21)
spring.threads.virtual.enabled=true